package api

import (
	"net/http"

	paymentHandler "vibe-ddd-golang/internal/application/payment/handler"
	userHandler "vibe-ddd-golang/internal/application/user/handler"
	"vibe-ddd-golang/internal/common/enum"
	types "vibe-ddd-golang/internal/common/type"
	"vibe-ddd-golang/internal/pkg/middleware"
	"vibe-ddd-golang/internal/pkg/response"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"

	_ "vibe-ddd-golang/internal/server/api/docs" // generated by swag
)

type Server struct {
	userHandler    *userHandler.UserHandler
	paymentHandler *paymentHandler.PaymentHandler
	logger         *zap.Logger
}

func NewServer(
	userHandler *userHandler.UserHandler,
	paymentHandler *paymentHandler.PaymentHandler,
	logger *zap.Logger,
) *Server {
	return &Server{
		userHandler:    userHandler,
		paymentHandler: paymentHandler,
		logger:         logger,
	}
}

func (s *Server) SetupRoutes(router *gin.Engine) {
	// Global middleware chain: CORS, then requestId/startTime, then the
	// response `send` installer, then panic recovery — all emit the standard envelope.
	router.Use(middleware.CorsMiddleware())
	router.Use(middleware.RequestInit())
	router.Use(middleware.ResponseInit())
	router.Use(middleware.Recovery())

	// Swagger documentation.
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.GET("/docs", func(c *gin.Context) {
		c.Redirect(http.StatusFound, "/swagger/index.html")
	})

	// Health at the root, outside the API prefix.
	router.GET("/healthz", s.healthCheck)
	router.GET("/readyz", s.readinessCheck)

	// API routes under /api/v1.
	apiV1 := router.Group("/api/v1")
	{
		s.userHandler.RegisterRoutes(apiV1)
		s.paymentHandler.RegisterRoutes(apiV1)
	}
}

// healthCheck godoc
// @Summary Liveness probe
// @Tags health
// @Produce json
// @Success 200 {object} types.ResponseAPI
// @Router /healthz [get]
func (s *Server) healthCheck(c *gin.Context) {
	response.Send(c, &types.Response{
		HTTPStatus: http.StatusOK,
		Code:       enum.CodeOK,
		Message:    "healthy",
		Data:       gin.H{"service": "vibe-ddd-golang-api", "version": "1.0.0"},
	})
}

// readinessCheck godoc
// @Summary Readiness probe
// @Tags health
// @Produce json
// @Success 200 {object} types.ResponseAPI
// @Router /readyz [get]
func (s *Server) readinessCheck(c *gin.Context) {
	response.Send(c, &types.Response{
		HTTPStatus: http.StatusOK,
		Code:       enum.CodeOK,
		Message:    "ready",
		Data:       gin.H{"database": "ok"},
	})
}
